### ISSUE TITLE
enhanced mode not working

### ISSUE THREAD

**Issue by dave-trudes** [PredixDev/px-popover#11]
## Expected behavior and actual behavior:
px-popover content not rendered when enhanced = true.

## Steps to reproduce the problem:
See codepen: https://codepen.io/anon/pen/pwpypz

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Chrome Version 58.0.3029.110 on Mac

**Comment by randyaskin** [comment]
The popover itself is fine, it's just the CodePen that's an issue. In fact, all of our CodePens seem to be broken due to an update to webcomponentsjs that probably coincided with the release of Polymer 2.

**Comment by dave-trudes** [comment]
Thanks.
I've changed the base URL of polygit to `https://polygit.org/polymer+v1.9.2/px-*+PredixDev+*/components/`. Now everything works as expected.
