### ISSUE TITLE
Popover not opening

### ISSUE THREAD

**Issue by dave-trudes** [PredixDev/px-popover#12]
## Expected behavior and actual behavior:
Popover should open even if the click event target is a child element of the trigger element.

## Steps to reproduce the problem:
See codepen: https://codepen.io/anon/pen/pwpypz
Clicking on the child element (red) will not open popover.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Chrome v.59.0.3071.115 on Mac

**Comment by randyaskin** [comment]
The API page clearly states that they must be siblings, as currently implemented.
https://www.predix-ui.com/#/components/px-popover/

**Comment by davidsteinberger** [comment]
IMO it's as easy as changing the event-target. Talking about events: The current implementation of the descendant check may not work w/ shadow-dom. Can I send a PR for both?

**Comment by randyaskin** [comment]
Feel free. But this component and px-tooltip should probably just be refactored to use iron-dropdown the same way we've done with the px-dropdown redesign, it handles the show/hide/positioning pretty elegantly.

**Comment by davidsteinberger** [comment]
ping

**Comment by randyaskin** [comment]
Hi @davidsteinberger, sorry for the delay. We're fully focused on releasing the design refresh across the entire system this week, we'll have to revisit this pull request when we have some more bandwidth

**Comment by victorbucutea** [comment]
@randyaskin  I think that the fix for this issue is pretty simple. 

In the _toggle() method at line 273 you check the id of the _event.target_ instead of _event.currentTarget_.

_event.currentTarget_ would contain the element on which the listener was defined, thus after a click on any of its children the if condition would properly recognize the id of the 'for' attribute compared against the 'id' of the element which listens for the click. Hope it's clear.

**Comment by randyaskin** [comment]
@victorbucutea Yes, I think that would work. Also thought of searching the event path. I ended up using a convenience method that Runn (I assume) had already written for this component, but any of those 3 methods should work I think. https://github.com/PredixDev/px-popover/commit/ef77c935efb6eb2626d471f9ed569e362eee0e02

**Comment by randyaskin** [comment]
See #19
