### ISSUE TITLE
Popover appearing in the wrong place

### ISSUE THREAD

**Issue by mmorton16** [PredixDev/px-popover#15]
## Expected behavior and actual behavior:

When clicking on the button in the demo for `px-popover`, I expected the popover to be directly adjacent to the button. Instead, it's appearing far away on the screen, per this screenshot:

<img width="1217" alt="screen shot 2017-08-29 at 10 11 10 am" src="https://user-images.githubusercontent.com/22401611/29825467-843402d2-8ca2-11e7-8647-8efd38e3d824.png">

This is also the case when I scroll down on the page and click on the button again:

<img width="1022" alt="screen shot 2017-08-29 at 10 14 06 am" src="https://user-images.githubusercontent.com/22401611/29825580-da74546c-8ca2-11e7-98a8-bdeadedf9939.png">

## Steps to reproduce the problem:

Click the "Click here" button in the [demo](https://www.predix-ui.com/#/elements/px-popover).

## Environment:

Using Google Chrome for `px-popover` v2.0.3.

**Comment by randyaskin** [comment]
Fixed in v2.0.4.
