### ISSUE TITLE
Position of popover is offset relative to page scroll position

### ISSUE THREAD

**Issue by squidbe** [PredixDev/px-popover#16]
## Expected behavior and actual behavior:
Expected: Popover position should be in the same relative position regardless of scroll location of page.
Actual: Popover position is offset by the same amount of the scroll offset (see screen shot)

## Steps to reproduce the problem:
Simply use your demo (https://www.predix-ui.com/#/elements/px-popover), and scroll down a bit, then click the "Click here" button.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
v.2.0.3 (2.0.4?)
Chrome 61
Mac El Capitan

## Screenshots (_optional, but very helpful_):
![screen shot 2017-10-09 at 4 20 11 pm](https://user-images.githubusercontent.com/1664227/31362521-c725b258-ad0d-11e7-8c1b-52dfca191309.png)

**Comment by davidrleonard** [comment]
Seems like we've got more positioning calculation weirdness. Looks like this regression started in c50fbbab332d1f298dcdaeeb350c98147cb7c102, which was filed to fix #15. But that fix is causing this bug. We'll need to investigate more.

**Comment by randyaskin** [comment]
Always good when the "solution" is ripping out more code, see v2.0.5. Ideally, we should move over to iron-dropdown for its dynamic alignment, but I _think_ this is fixed for now. Let me know if you see any other positioning weirdness.

**Comment by randyaskin** [comment]
My fix works in isolation, but not when the component appears on predix-ui.com. Need to look into a longer term solution / refactor of this component.

**Comment by victorbucutea** [comment]
Same problem here. When I bind the _px-popover_ on an absolutely position element ( using its id in the `for` attribute ), the resulting popover is positioned relative to my element, instead of relative to the top of the screen, resulting in the popover being displayed further below.

**Comment by randyaskin** [comment]
I've started a branch that uses iron-dropdown for more sane positioning logic (regardless of relative/absolute). Also switched from content to slot. The only issue I'm having is that I had to add a small timeout before calculating the width of the popover (iron-dropdown uses display:none so I can't measure it while it's hidden). @squidbe @victorbucutea please feel free to take a look and let me know if you have any ideas - https://github.com/PredixDev/px-popover/tree/irondropdown

**Comment by benoitjchevalier** [comment]
regarding the setTimeout you might be able to get around it by listening to "iron-overlay-opened" which should fire after the thing has been opened (he says without having tried...)

**Comment by randyaskin** [comment]
That might work if the overlay weren’t optional and turned off by default, I don’t think most teams use the overlay.

**Comment by benoitjchevalier** [comment]
Ah good point, I was wrongly assuming it was tied to the opening of the content

**Comment by randyaskin** [comment]
No longer an issue in v2.2.0 as we no longer calculate positioning ourselves, relying on iron-dropdown instead.
