### ISSUE TITLE
Enhancement Request: New custom attributes

### ISSUE THREAD

**Issue by squidbe** [PredixDev/px-popover#18]
Can you please add two attributes to enable customization of the div with id="popover":
1) background
2) box-shadow

I know you already expose background-color; if you expose the "background" shorthand, I can easily set all the background attributes. Specifically, I need to be able to use a linear-gradient on the background as well as setting things like repeat, position, etc.
Thanks!

**Comment by randyaskin** [comment]
Not sure how our designers would feel about gradient popovers, but it's backwards compatible, so ¯\_(ツ)_/¯  See v2.0.7.
