### ISSUE TITLE
Doesn't work with px-icons.

### ISSUE THREAD

**Issue by rupeshambati** [PredixDev/px-popover#19]
How to reproduce.

https://github.com/PredixDev/px-popover/blob/master/demo/px-popover-demo.html

Just change Line:39 to the below snippet.

`<px-icon id="{{props.for.value}}" icon="px-utl:help"></px-icon>`

**Comment by randyaskin** [comment]
Since the target of the click events was actually the child element (iron-icon), it was treating those as "outside" clicks. Fixed in v2.0.6 to check if the click target is the trigger element or one of its children.
