### ISSUE TITLE
light-dom for enhance property does not render within html table

### ISSUE THREAD

**Issue by jaclynadams** [PredixDev/px-popover#6]
## Expected behavior and actual behavior:
Expected: with `enhance="true"` should render custom html inside of popover

Actual: `enhance="true"` shows an empty popover when popover used within a table

## Steps to reproduce the problem:
Use a px-popover component inside of an html table with `enhance="true"` and light-dom content to be applied.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-popover v1.7.3
Chrome Version 55.0.2883.95 (64-bit)
OSX
Polymer v1.7.0

## Screenshots (_optional, but very helpful_):
Expected (used outside table):
![image](https://cloud.githubusercontent.com/assets/9424436/22673338/6448d308-ec8e-11e6-8eaa-75ca996c39e8.png)

Actual (used inside table):
![image](https://cloud.githubusercontent.com/assets/9424436/22673328/52d5f47a-ec8e-11e6-9161-5ebcfcb90a38.png)

**Comment by randyaskin** [comment]
I'm not able to replicate your issue. Here's a CodePen of popover working just fine within an HTML table with light DOM content: http://codepen.io/randyaskin/pen/NdoPQw?editors=1001

FYI the property is `enhanced` not `enhance` - maybe just a typo?
