### ISSUE TITLE
Popover can get truncated

### ISSUE THREAD

**Issue by benoitjchevalier** [PredixDev/px-popover#7]
likely because of hyphens: auto; in sass.

Problem can be seen in pie chart:
![image](https://cloud.githubusercontent.com/assets/3206342/23032586/b2abebe6-f429-11e6-9ee3-6306d3f5575b.png)

**Comment by davidsteinberger** [comment]
IMO the truncation is caused by the hypens-style-property on the paragraph. Could that be changed to

    #popover p {
      hyphens: none;
      white-space: nowrap;
    }

**Comment by benoitjchevalier** [comment]
Agreed,  although I think this was put in as a way to have the popover wrap for very very long word reaching the 250px width limit. So we need to make sure we're not breaking that behavior.
I think there's been a recent change exposing that max-width limit but the text should still wrap when longer than the max width

**Comment by randyaskin** [comment]
I replaced `hyphens: auto` with `word-wrap: break-word` which is what we use in tooltip, data-table, and others. The popovers still look a little thin in pie chart, seems like they may need a min-width or width in addition to max-width?

**Comment by benoitjchevalier** [comment]
Closing this as this is not overflowing anymore. We can discuss the popover being too thin in certain cases in another thread (i.e introduce a min-width)
